### ISSUE TITLE
problem with hungarian orthophotos in id

### ISSUE THREAD

**Issue by szzyx** [osmlab/editor-layer-index#1022]
Hi, it seems like the FÖMI orthophoto backgrounds are not loading in the online iD editor, neither the 2005 nor the 2007-2010 ones. I've first noticed this problem maybe back in november, but back then i thought it was some temporary error. However, today, this time on another pc, I still could not use these backgrounds since the entirety of hungary is blacked out on them. Is there maybe a problem with these layers or could it be that i am just missing something very obvious?

**Comment by rbuffat** [comment]
This URL works:
http://e.tile.openstreetmap.hu/ortofoto-2007-2010/18/145005/92033.jpg

but with HTTPS it does not work: 
https://e.tile.openstreetmap.hu/ortofoto-2007-2010/18/145005/92033.jpg

When I test it in Chrome iD tries to access the data with HTTPS, which does not work. Not sure if it's chrome or iD that does the switch, the sources are specified as HTTP in ELI.

**Comment by rbuffat** [comment]
@szzyx If you use Chrome as a browser, it is most likely due to Chrome forcing https and tile.openstretmap.hu not supporting it. See also https://github.com/openstreetmap/iD/issues/8299

As a workaround, you can use a browser not forcing https or configure Chrome to not doing it for this domain.  See also the comment by @tordans: https://github.com/openstreetmap/iD/issues/8299#issuecomment-760658194
