### ISSUE TITLE
TIGER 2012 overlay

### ISSUE THREAD

**Issue by kreed** [osmlab/editor-layer-index#106]
It doesn't look like this is working anymore. Should it be removed?

**Comment by iandees** [comment]
The database on the server that ran this was corrupted and so needs to be rebuilt. It just so happens that the person who would do such a thing (me) has been on vacation or working for the last 3 weeks since it happened so I haven't had time to fix it. Hopefully I'll be able to do something about it this week.

**Comment by kreed** [comment]
I see. Sounds good.

**Comment by bhousel** [comment]
TIGER 2012 looks to be ok now.. closing..
