### ISSUE TITLE
How to order imagery layers?

### ISSUE THREAD

**Issue by AntMadeira** [osmlab/editor-layer-index#1369]
Recently, some imagery layers were added to iD, but some mappers are complaining that CyclOSM, for example, is the second layer in the list now, which shouldn't have such priority position. Is there a way to organize the layers for a given country by relevance in descending order?

**Comment by simonpoole** [comment]
ELI has a best flag, however it is really only useful for ranking in a category. 

That said there is no real issue in creating a reasonable order from the available data (category, coverage, age and the best flag), the problems you are seeing are maybe due to the layer not being filtered out pre-build which is what I kind of remember ID doing for 'map' layers.

In any case it's an ID issue.

**Comment by rbuffat** [comment]
@AntMadeira As @simonpoole already mentioned this looks like an issue with iD. Please create an issue in the projects issue tracker: https://github.com/openstreetmap/iD/issues

I guess it is an issue that there is a growing number of layers in the index, and mappers might judge the importance of layers differently. If there is something that could help in filtering / identifying the usefulness of imagery sources we should definitively think about it.

E.g. we could generate for each source an ordering of recentness for each source based on the min/max years, category, and the imagery boundary. E.g. 0 = most recent imagery for the same category. 1 = second most recent imagery, etc. 

CC @tyrasd

**Comment by AntMadeira** [comment]
Thank you, @simonpoole and @rbuffat. I'll open a new issue with iD.

**Comment by tyrasd** [comment]
there already exists issue https://github.com/openstreetmap/iD/issues/8814 (and potential fix/improvement in pull request https://github.com/openstreetmap/iD/pull/8826) for this.
