### ISSUE TITLE
Add Stamen terrain

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#143]
About: http://mike.teczno.com/notes/osm-us-terrain-layer/foreground.html
Tiles: http://maps.stamen.com/terrain/#12/37.7706/-122.3782
Code: https://github.com/Citytracking/Terrain
Template:  http://{switch:a,b,c,d}.tile.stamen.com/terrain/{z}/{x}/{y}.jpg

USGS Topographic has holes in coverage and doesn't really have great detail at the zoom levels where people trace in iD.  Stamen Terrain looks great all across North America..

@pnorman is this ok?  Tiles seem to be CC-BY 3.0.
@migurski is it ok to include this as a background source for tracing in iD and other editors?

**Comment by migurski** [comment]
Hi, this is a great use of Terrain, happy to see it! @mojodna might be better informed about current issues though.

**Comment by almccon** [comment]
Hi @bhousel, what features in Stamen Terrain do you find useful? Just the hillshade I assume?

Current Stamen Terrain is license compatible with OSM. It's basically OSM data + a hillshade derived from [NED](https://lta.cr.usgs.gov/NED) + and the landcover is also from USGS, I think, so those are both in the Public Domain.

Since the road data in Stamen Terrain is already from OSM, you wouldn't want to trace that. Plus, it's extremely old (circa 2012), which is even worse: people might see features in Stamen Terrain and try to trace them, only to find that they've been deleted from OSM itself long ago (either because they were wrong in the first place, or because the real-world feature has changed).

So you probably want to use `terrain-background` http://maps.stamen.com/terrain-background which has just the hillshade, plus landcover, plus some OSM area features like parks and such.

Oh, one last thing: Stamen Terrain is really just for the US only. It has landcover and OSM data for Canada and Mexico, but no hillshades there.

At Stamen we are working on a reboot of Stamen Terrain which will be for the whole world, and eventually we will serve that up as a drop-in replacement.

**Comment by bhousel** [comment]
Hey @almccon!   Yes, I'm primarily interested the hillshade.  I agree that `terrain-background` is the right style to support iD and other editors.  Roads aren't needed because at lower zooms we can show the transparent "locator overlay", which is updated frequently with current OSM road and place data.

The usecase for this is to see elevation data, which can helpful for hydrography mappers to know which way rivers flow.  There was a [recent thread on the HOT mailing list](https://lists.openstreetmap.org/pipermail/hot/2016-April/011445.html), but this is something that I'm asked about every few months.  Making this layer available in US only for now is ok, but a reboot of Stamen Terrain with worldwide terrain coverage would be fantastic..

Some mappers use the [OpenCycleMap style](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/OpenCycleMap.json) for this kind of tracing, as it does have worldwide coverage and displays contour lines, however the style displays plenty of other features and isn't really designed for this.  cc @gravitystorm - would you want any of your other styles included in the editor-layer-index project?  I don't see a reason to have more than one or two terrain background sources in iD, but this imagery index is also used by Potlatch and maybe others?

**Comment by imagico** [comment]
Few notes on use of topographic data for mapping:

* yes, this can be very useful for river mapping, especially for determining drainage directions in relatively flat areas and ambiguous situations near watersheds as well as steep mountain areas with shadows in imagery layers.
* this works much better with low noise data like manually photometrically derived or well processed LIDAR data so NED etc. are usually more useful than SRTM/GDEM.
* shaded rendering, especially the very simple local linear lambertian and pseudo-specular type depictions are of fairly limited use for this purpose.  These can help the mappers in broad orientation but are of little use for mapping decisions in detail.
* Of the currently deployed map styles i consider the opentopomap style as best for mapping purposes. See for example

http://dev.opentopomap.org/#map=11/50.3231/89.3127

for an area of possible application.  Unfortunately there is no worldwide coverage in the main version and performance is not really as you'd want it for mapping (cc @der-stefan).

**Comment by bhousel** [comment]
@imagico, @der-stefan - Nice, that opentopomap style is ideal for what I'm looking to add!  Yes, performance looks like an issue.  I'm not sure who to approach about improving that - I guess either opentopomap would need additional resources to cache and bake the tiles down to higher zooms, or we'd need to find a donor to host that style someplace that can do it?

**Comment by der-stefan** [comment]
@imagico Thanks for the commendation. We have more resources than what we use. OpenTopoMap could in fact be worldwide, up-to-date and fast. The problem is not the hardware, but the software. For example renderd/mapnik only runs in one thread. Don't ask me why it crashes with more threads. And this is the main problem: I am the only developer and don't have too much time to investigate those issues. If someone wants to clone OpenTopoMap, just do it! Perhaps I will find some time and mood and work on. Perhaps it takes months - I can't tell.

**Comment by bhousel** [comment]
Thanks everyone for your comments - for now I've added Stamen's `terrain-background` tiles for use within US only.

@der-stefan, @imagico, @gravitystorm and others, if you ever want your tiles added to the OSM editors please open an issue or pull request - you do beautiful work and we'd love to support them if the resources to serve the tiles become available.  :+1:
