### ISSUE TITLE
Add Maryland Statewide Orthophotos

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#148]
*I can do this as a PR, but for now here's a descriptive format*.

Maryland's 2013 and 2014 orthophotography is public domain high resolution data that can be used for OSM.

The image server URL is at http://geodata.md.gov/imap/rest/services/Imagery/MD_SixInchImagery/MapServer/

An example map tile using the zoom,x,y format is http://geodata.md.gov/imap/rest/services/Imagery/MD_SixInchImagery/MapServer/tile/14/332500/146384

Notice that the project is `epsg:3857`, the same as OSM. The tile coordinates appear to be in a NAD83 style.

**Comment by bhousel** [comment]
Thanks @talllguy, I did look into this a bit today.  You're right that the tile coordinates are not OSM compatible on this source.  They use 512px tilesize and origin is not 0/0/0.

So we'd need to use something like whoots to query their WMS server directly.

Unfortunately whoots still requests `srs=EPSG:600613` instead of the more standard `srs=EPSG:3857` (see timwaters/whoots#1), and this Maryland WMS server doesn't accept the 600613 alias.. 

but if they did - the template would look like this

`http://whoots.mapwarper.net/tms/{z}/{x}/{y}/MD_SixInchImagery/http://geodata.md.gov/imap/services/Imagery/MD_SixInchImagery/MapServer/WmsServer`

**Comment by bhousel** [comment]
@timwaters fixed the upstream issue with whoots, so I added this source today.

**Comment by talllguy** [comment]
@bhousel question: It looks like @simon04 was able to add the Maryland Three Inch Orthos (#206) without using the proxy. Could this source be changed to remove the proxy?

I thought that this could reduce the load on whoots, if it is not needed.

**Comment by simon04** [comment]
The con of using the WMS directly is that the imagery is not available in iD, see https://github.com/openstreetmap/iD/issues/1141

**Comment by talllguy** [comment]
Got it. Thanks for the info!

**Comment by talllguy** [comment]
@msokolDOIT here is the item we discussed at TUgis. This issue led to the inclusion of the Maryland Imagery in OpenStreetMap.
