### ISSUE TITLE
PCN Italy not working

### ISSUE THREAD

**Issue by ElDavoo** [osmlab/editor-layer-index#1492]
Is it just me or are the PCN Italy sources not working?

**Comment by tyrasd** [comment]
Today the PCN 2006 and 2012 layers work for me. The service could have been just temporarily down.

**Comment by ElDavoo** [comment]
why?? how??? it does not work for me. i get timed out in iD.

**Comment by tyrasd** [comment]
OK, the service actually seems to be quite unreliable. Two days ago it worked fine for me, but today I get a mix of tiles that load successfully but also a lot of `503 Service Unavailable` errors (the error message includes that: _The server is temporarily unable to service your request due to […] capacity problems. Please try again later._). I didn't see any requests time out, though.

//cc @napo @lucadelu - do you maybe know if this is a permanent state and/or if there is a workaround to access the tiles?

**Comment by rbuffat** [comment]
@tyrasd The server seems to have quite strict limits regarding requests: https://wiki.openstreetmap.org/wiki/Italy/PCN#Prevenire_il_blocco_dell'accesso_al_server_WMS

AFAIK iD sends a request for each TMS tile, thus this limit is reached quite fast.
