### ISSUE TITLE
OSM standard layer in black & white needs new source URL?

### ISSUE THREAD

**Issue by stephan75** [osmlab/editor-layer-index#167]
So far we have in this list:

world / OpenStreetMap (Standard Black & White)

URL: url: http://{switch:a,b,c}.www.toolserver.org/tiles/bw-mapnik/{zoom}/{x}/{y}.png

IIRC toolserver.org was closed / moved many month ago.
So Vespucci editor does not display them as background.

new URL can be:
tms[18]:https://tiles.wmflabs.org/bw-mapnik/{zoom}/{x}/{y}.png ... as listed in JOSM?

**Comment by Lee-Carre** [comment]
I notice that the supplied tiles are now quite outdated.

However, [Parking Lanes](https://zlant.github.io/parking-lanes/) shows grayscale tiles which are based on much more recent data.

I'm not sure where they're hosted or what the URL pattern is (I'm limited to using an Android device for the time being).

Might it be possible to update ELI to use the URL of the newer tiles, so that they're literally just a desaturated rendering of the standard coloured tiles, while maintaining parity in terms of data represented?

**Comment by Lee-Carre** [comment]
> I'm not sure where they're hosted or what the URL pattern is

Digging into their source-code a bit yielded the following:

    https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

from [parking-lanes/src/parking/interface.js#L56](https://github.com/zlant/parking-lanes/blob/abca2854de6e72ff81d9e9cb781adf149432717a/src/parking/interface.js#L56).

Although, since that seems strikingly similar to the URL for colour tiles, despite the relevant layer being named mapnik_gray, might that mean that they're simply desaturating the tiles themselves?

A bit out of my depth as a relative newbie to OSM.
