### ISSUE TITLE
Just make this JavaScript already

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#168]
Does anyone have any serious objections if I replace the (very few) Python scripts in this repository with JavaScript?  It would make things so much easier with testing, publishing, dependency management, etc?

JavaScript ate the world already, lets just use it.  This whole repo is JSON files anyway.

**Comment by iandees** [comment]
Heh, maybe it ate *your* world... My world is still squarely snake-like.

Yup, switching to node is fine. Let me know if I can help.

**Comment by simon04** [comment]
@bhousel: is there a (public) branch regarding your script-to-JavaScript migration?

**Comment by bhousel** [comment]
> is there a (public) branch regarding your script-to-JavaScript migration?

No, I haven't started.. I've been focused mainly on iD v2, which I'd like to release in time for osmgeoweek.  

It really helps me out a lot to be able to include your improvements to editor-layer-index.  👍   Just wanted to say thank you!

**Comment by rbuffat** [comment]
ELI evolved to have more advanced CI checks implemented with Python. Imho Python is an adequate language for this use case as it is heavily used for data analysis/data science and has excellent support for spatial data processing. That being said, I'm more experienced with Python than Javascript and there is this saying that if you only have a hammer everything looks like a nail. 

Probably most things could also be implemented with Javascript, but at least one thing I'm aware of that there is currently no good library available for coordinate transformations (Proj4js seems to have troubles with some projections).

As this issue is quite old I'm closing it for now.

**Comment by bhousel** [comment]
I have no idea why a project that smooshes together a few hundred json files needs to perform projections, but ok.

**Comment by rbuffat** [comment]
> I have no idea why a project that smooshes together a few hundred json files needs to perform projections, but ok.

That's the reason, it's now not just smooshing a few hundred JSON files together anymore.

E.g. there is a bot now that weekly checks all WMS server-based sources, which checks advertised and not advertised projections. This is done by downloading test images for each projection (which requires projections) and comparing them using ImageHashes.  If you are curious: https://github.com/osmlab/editor-layer-index/blob/gh-pages/scripts/sync_wms.py
