### ISSUE TITLE
Re: OSIP Imagery Problem

### ISSUE THREAD

**Issue by Korgi2** [osmlab/editor-layer-index#1858]
New Info regarding https://github.com/osmlab/editor-layer-index/issues/1809

I have received a email from someone at the Ohio GIS

"Please try this service https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP/OSIPIII_MostCurrent/ImageServer
Or the wms here https://geo1.oit.ohio.gov/arcgis/services/OSIP/OSIPIII_MostCurrent/ImageServer/WMSServer?request=GetCapabilities&service=WMS"

Is this of any use? I have no idea how to make use of this or if it solves the issues for the tiles or not.

**Comment by Korgi2** [comment]
While it is geoblocked outside the United States, the WMS could be used to supplement the existing OSIP III imagery preset as I and others verified it works.

**Comment by 1ec5** [comment]
#1979 adds the recommended layer (which is better than all the ones we had been listing). However, I’m not confident that it solves the geoblocking issue, since it’s on the same domain as the others.

Assuming the server still blocks requests by overseas mappers, then OSMUS runs an [ArcGIS server proxy](https://ags-proxy.openstreetmap.us/) that should be able to overcome this limitation. Enter `https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP/OSIPIII_MostCurrent/ImageServer` as the ArcGIS server URL, verify that a drab green Ohio appears on the map, and copy the proxy URL template into your editor of choice.
