### ISSUE TITLE
Overlapping "best" imagery

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/editor-layer-index#2076]
Hi,
Flanders is a multipolygon: the Brussels region is within it, but is not part of Flanders.
For some geodata, the Flemish region just covers Brussels as well (as sometimes that's just practical).
The [Flemish imagery](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/be/DV_OrthoPhoto.geojson?short_path=5351b40) that is marked as best, also covers Brussels. But [the imagery that the Brussels region provides](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/be/UrbIS_OrthoPhoto.geojson?short_path=6edd8fa) is actually better and of course also marked as best. In iD, the editor defaults to the Flemish imagery, which is a bit of a pity.
Maybe this is more of an iD issue, but perhaps it'd make sense to prefer imagery that has a smaller footprint over the larger dataset, all else being equal.
I guess we could split the Flemish imagery in two ELI objects, with the Brussels part not marked as best.
Any other suggestions for solutions?

**Comment by simonpoole** [comment]
The issue turns up because iD automatically shows the "best" imagery and even if it increased the importance for smaller coverage areas (which other editors do) doing so can always lead to unsatisfactory results, simply because the choice of the actually "best" imagery is complicated. 

My preferred solution is to ask the user to make an informed decision within ranked imagery sources and to not provide a default imagery source.

**Comment by joostschouppe** [comment]
Turns out the issue in Brussels has been fixed some time ago already
