### ISSUE TITLE
[Watchdog] Imagery "Hennepin County Orthoimagery (2022)": sources/north-america/us/mn/Hennepin_Ortho_2022.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#2158]
Watchdog failed for 5 consecutive days for:
"Hennepin County Orthoimagery (2022)" -> [sources/north-america/us/mn/Hennepin_Ortho_2022.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/mn/Hennepin_Ortho_2022.geojson)

Reason:
Error: WMS -: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0 Error: Could not parse XML.
Error: WMS -: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?service=WMS&request=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://gis.hennepin.us/arcgis/services/Imagery/UTM_Aerial_2022/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.0.0 Error: Could not parse XML.

CC contributors to this imagery:
@gvwaal

**Comment by gvwaal** [comment]
I can't figure out how to get this imagery to load in OSM and would appreciate any assistance from @rbuffat, @cicku, or perhaps @aaronlidman.

[This is the resource](https://gis.hennepin.us/arcgis/rest/services/Imagery/UTM_Aerial_2022/MapServer) I'm trying to add. The WMS referenced in this Issue is no longer offered, but a WMTS is.

[King County Orthoimagery (2021)](https://github.com/osmlab/editor-layer-index/blob/e66a8077d3ace8a6dcdbd9060db4f5199d74e95f/sources/north-america/us/wa/King_WA_2021.geojson?short_path=379fad4) is a similar functioning service ([resource](https://gismaps.kingcounty.gov/arcgis/rest/services/BaseMaps/KingCo_Aerial_2021/MapServer/)). That imagery's `url` successfully loads imagery when added as a custom layer in OSM's iD editor. Based on the King County `url`, the `url` for Hennepin County 2022 should be [1], but this does not load imagery when added as a custom layer in iD - specifically, it returns 400 errors in Firefox's console. Hennepin County 2022 does load imagery when added in QGIS.

Furthermore, the URL that actually returns imagery looks like [2], but using this URL format as a custom layer while substituting the latter three numbers for zoom/x/y doesn't load imagery in iD, and returns 404 errors instead.

I can't tell whether I'm missing something or there's something about the Hennepin County imagery that makes it unuseable with OSM.

[1] https://gis.hennepin.us/arcgis/rest/services/Imagery/UTM_Aerial_2022/MapServer/WMTS/tile/1.0.0/Imagery_UTM_Aerial_2022/default/default028mm/{z}/{y}/{x}

[2] https://gis.hennepin.us/arcgis/rest/services/Imagery/UTM_Aerial_2022/MapServer/tile/8/1670184/1471017

**Comment by arch0345** [comment]
Unfortunately, tms only works for sources that use Web Mercator (EPSG:3857). Since this source uses EPSG:26915, the only way to use this is using ArcGIS MapServer exporting such as what we're doing with [San Juan County](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/wa/San_Juan_WA_2022.geojson).

**Comment by gvwaal** [comment]
Thanks for the reply and for sharing that knowledge! The new URL in #2172 works for me.
