### ISSUE TITLE
Add NY State orthos ("latest" layer)

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#345]
When **requesting the addition of an imagery layer**, please provide the following information. Otherwise, delete the text and type your issue.

## URL of the imagery
http://www.orthos.dhses.ny.gov/ArcGIS/rest/services/Latest/MapServer/

see also
https://gis.ny.gov/gateway/mg/webserv/webserv.html
https://gis.ny.gov/gateway/mg/metadata.cfm
https://gis.ny.gov/gateway/mg/nysdop_descrip.htm
https://gis.ny.gov/gateway/orthoprogram/index.cfm  (6" available in many areas now)

## Two letter country code
US - NY

## Desired layer name
any

## License
unclear - needs investigation

## Is the license compatible with OSM?
Not sure

**Comment by kennykb** [comment]
Several emails to the program manager for NYS Digital Orthoimagery in the autumn went unanswered, alas. Nevertheless, at long last, I found [metadata in Open NY.](https://data.ny.gov/Public-Safety/Statewide-Digital-Orthoimagery/amsv-rmfz)  It includes the line:

> **Limitations** | No limitations on use of publicly available imagery.

(That's also in the XML metadata. I missed it the first time because I was looking for a License element, and there was none; this is in the Disclaimers element. Oh well, its not the only time that someone didn't quite follow a schema.)

I think we can take this as an indication that the data are in the public domain. I was about 95% sure of this, owing to the express written policies of Gov. Cuomo and the NYS Committee on Open Government, but was trying to get further assurance. With an explicit 'no limitations on use' policy in the metadata, I think we're good to go.

And I'm eager to get started, because the 2017 data for my county are up and will allow me to correct some questionable tracings. This is the only really good source for 'leaves down' imagery that I've been able to find. (Comparing summer and winter images is incredibly useful when tracing.)

You already have the link up above to the [description of the tile server](http://gis.ny.gov/gateway/mg/webserv/webserv.html). 

How can I help further?
