### ISSUE TITLE
feat(i18n): please enable i18n of more imageries

### ISSUE THREAD

**Issue by manfredbrandl** [osmlab/editor-layer-index#346]
@bhousel Can you please add two more imagery texts to transifex?
![image](https://user-images.githubusercontent.com/5360273/27293153-dfaf6f12-5515-11e7-8786-a3459dd9566b.png)
![image](https://user-images.githubusercontent.com/5360273/27293198-fad610ac-5515-11e7-837d-cb982f19e93c.png)

**Comment by bhousel** [comment]
Sure, just added it..

**Comment by bhousel** [comment]
Well that's interesting.. Because the key has a dot in it, transifex needs to escape it.  I'll double-check to make sure that iD handles this key ok.  If I need to change something on the iD side to tolerate keys with dots in them, I'll open a separate issue.

<img width="642" alt="screenshot 2017-06-19 15 40 10" src="https://user-images.githubusercontent.com/38784/27302693-2675abec-5506-11e7-955c-504c7d1200a2.png">

**Comment by manfredbrandl** [comment]
@bhousel 15 Minutes after translating the texts with key ...<TX_DOT>... the preview still shows the english names.
