### ISSUE TITLE
Best-best image for region?

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#390]
The best imagery for Luxembourg is currently 25 cm imagery from 2017. We've [recently gotten 10 cm imagery from a lidar test region](https://twitter.com/i/web/status/954283037549846530). 

What's the proper way to mark the 10 cm imagery as the very very best imagery for this part of the country, while still having the 25 cm imagery marked as second best for the whole country?

## URL of the imagery
https://data.public.lu/en/datasets/lidar-projet-pilote-dun-releve-3d-du-territoire-luxembourgeois/

## Desired layer name
Ettelbrück - Diekirch 2017

## License
CC-0

## Is the license compatible with OSM?
Oh yeah

**Comment by simonpoole** [comment]
This depends on the consumer of the index. I sort first on the best flag and then on the end date. So for me setting the best flag on both and setting correct end dates would give the correct order.

**Comment by grischard** [comment]
It looks like [iD sorts by area size, preferring smaller areas](https://github.com/openstreetmap/iD/blob/fb196bee8c391bcc3cd5ee1d070027e3692f546d/modules/ui/background.js#L191).

So @simonpoole there's no way to make more precise older imagery show up by default in Vespucci?

**Comment by simonpoole** [comment]
We don't show anything (outside of the standard style map layer) by default, so its not really such an issue, it simply affects the ordering in the imagery selection list (which only shows layers with coverage of the area, so typically has a few regional/local areas plus the global ones). Since the user -has- to make a choice of imagery it is less critical as if we would serve up something automatic.

I would argue that in the current regime, newer imagery that is not as good as older, should not have the best flag set. In any case we all know that the current scheme has some deficiencies, but it is a lot better than anything else that has been done in the past.
