### ISSUE TITLE
For imagery taken in one year, use same start and end year?

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#462]
`CONTRIBUTING.md` currently says:

> Implementations may round down the end date (e.g. consider `2013` the same as the
start of `2013` so to specify imagery taken sometime in 2013, use `"start_date": "2013"`,
`"end_date": "2014"`.

This is not instinctive, should be handled by data consumers, and seems to be ignored in practice. I had a look at past years, and only a minority of layers that only have a year as a start_date don't have the same year as an end_date. No such layers exist after 2015.

Ok to update `CONTRIBUTING.md` to reflect this?

**Comment by grischard** [comment]
See also #29

**Comment by bhousel** [comment]
Yes, I'd definitely welcome switching the start/end dates to have more intuitive meaning.  `start_date` and `end_date` can be the same.

iD doesn't sort imagery by date anyway (issue #29 was from 2013) and it's not something we would do now that we have 6 worldwide imagery layers for people to map from, each with a mix of old and new imagery.

**Comment by Klumbumbus** [comment]
(See also #286 for previous discussion)

**Comment by imagico** [comment]
> iD doesn't sort imagery by date anyway (issue #29 was from 2013) and it's not something we would do now that we have 6 worldwide imagery layers for people to map from, each with a mix of old and new imagery.

That is a somewhat strange statement - how does having six worldwide image layers with more or less opaque age of imagery make it less desirable to have the ability to prioritize images by date for mappers?  Maybe what you wanted to say is that the increasing number of layers with unknown dates make it increasingly unrealistic to do so.

The image acquisition date is the most important secondary information to have for a mapper on an image source, mainly because in contrast to other aspects of quality (extent, resolution, clouds etc.) it can not be readily assessed from the image itself.  Therefore i would - in an editor - always prominently show the date to mappers and warn them if no date information is available.

Also note the date problem will increase in the future because the range of dates available in image layers will widen.  We still have mappers wasting time tracing from 15-20 year old images because they are unaware of the age.  That will not stop unless we educate mappers about this.

**Comment by bhousel** [comment]
> That is a somewhat strange statement - how does having six worldwide image layers with more or less opaque age of imagery make it less desirable to have the ability to prioritize images by date for mappers? Maybe what you wanted to say is that the increasing number of layers with unknown dates make it increasingly unrealistic to do so.

Yes, I'm saying it's impossible to sort the list by age because each of those layers combine imagery of various ages and are constantly being refreshed in different places.

**Comment by grischard** [comment]
Heads up @simonpoole .
