### ISSUE TITLE
Automatically integrate https://api.openaerialmap.org/meta

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#509]
OpenAerialMap is an open collection of aerial imagery that we can use. The JSON at https://api.openaerialmap.org/meta should be automatically integrated.

**Comment by simonpoole** [comment]
The better thing to do would be to add the couple of missing attributes from ELI to the OAM schema and then run an instance with the contents of ELI.

As to including OAM in ELI, that doesn't seem to make a lot of sense since a client can directly query the OAM API (As for example Vespucci does). If at all then simply providing a copy of the OAM directly in ELI format would be the thing to do.

**Comment by cicku** [comment]
Done in #1649
