### ISSUE TITLE
Broken osmdata.asitvd.ch URLs

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#531]
_From @SelfishSeahorse on August 7, 2018 8:34_

Hello

The TMS URLs from osmdata.asitvd.ch in the file openstreetmap/iD/master/data/imagery.json don't work. According to <http://osmdata.asitvd.ch>, the protocol should be HTTP instead of HTTPS. (I've tested them; they do work.)

_Copied from original issue: openstreetmap/iD#5211_

**Comment by grischard** [comment]
This was fixed in d9f3847 6 days ago.

I'll hopefully have some time to improve the geojson build and test process today to make sure only good, valid, healthy, whole-grain geojson gets released. I'm still hoping that I can get it stable enough to convince you that iD can directly integrate the latest geojson, to prevent issues like this and be able to address them quickly if/when they happen.

Do you have like a checklist that you do on ELI when you do an iD release?
