### ISSUE TITLE
Make privacy_policy_url mandatory

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#690]
Currently only a very small number of sources have the privacy_policy_url set, even very new entries like the Maxar layer don't. 

This is an issue, not only, but particularly for the OSMF as using an editor on osm.org will not only transfer the IP address (which in itself is already personal data) and associated browser information, but also the viewed area to the imagery providers. Now we do disclose this in the OSMF privacy policy and point to here for more information, but that doesn't really help if nearly no layers have the information.

Best would be if the information would easily be accessible in the editor itself (something which Vespucci has had for a while), but I'm not holding my breath for that.

Naturally it will take a longish time for this to be available for all configurations, but we could start by requiring the information for any new or updated layers.

Thoughts?

**Comment by grischard** [comment]
So it's a bit like #439 ? I think most sources don't even *have* a privacy policy.

A nice travis lint script would be one that checks PRs for such attributes, yes.

**Comment by simonpoole** [comment]
> 
> 
> So it's a bit like #439 ? I think most sources don't even _have_ a privacy policy.
> 
> A nice travis lint script would be one that checks PRs for such attributes, yes.

Well, I was thinking more (the back log in #439 proving my point) that the build should fail and the corresponding PR not be mergable, if either of those URLs are missing. Naturally we can only change that going forward for sources that are modified or are new, the question is if we can determine the last changed data in a reasonable form. I suppose git could potentially be used for that.

**Comment by 1ec5** [comment]
> I think most sources don't even *have* a privacy policy.

This is often the case with state and local government agencies in the U.S. For example, the WMS added in #593 is provided by the state’s Department of Administrative Services, which has [a privacy policy](https://das.ohio.gov/Privacy) covering only the department’s homepage but [no privacy policy](https://ogrip.oit.ohio.gov/privacy.aspx) explicitly covering the WMS. Maybe ArcGIS Server doesn’t have a built-in setting for one.

When these agencies do have privacy policies, they [read very differently](https://ohio.gov/wps/portal/gov/site/home/privacy-notice-and-policies) than typical commercial privacy policies, because public records / open government laws sometimes work at cross purposes to personal data protection.

**Comment by simonpoole** [comment]
> 
> 
> > I think most sources don't even _have_ a privacy policy.
> 
> This is often the case with state and local government agencies in the U.S. For example, the WMS added in #593 is provided by the state’s Department of Administrative Services, which has [a privacy policy](https://das.ohio.gov/Privacy) covering only the department’s homepage but no privacy policy explicitly covering the WMS. Maybe ArcGIS Server doesn’t have a built-in setting for one.
> 
> When these agencies do have privacy policies, they [read very differently](https://ohio.gov/wps/portal/gov/site/home/privacy-notice-and-policies) than typical commercial privacy policies, because public records / open government laws sometimes work at cross purposes to personal data protection.

I don't think this is an unsolvable issue. The main point would be to get the privacy policy of those sources that do have one. For those that don't have one, determined after investigation by whoever wants to make the layer available, we can add an URL that points to a (dire) warning. Or we could use a special value that would signal that to the application using ELI.

Just to be clear, this is not really optional, it's the law (and in principle any application should be showing the privacy policy or the absence of one -before- switching to that layer).

**Comment by matkoniecz** [comment]
Maybe for start add complaint messages in a build script? That in future will be turned into fatal errors.

**Comment by grischard** [comment]
If you want to give it a go, `scripts/check.py` can easily be adapted - just use the code for `license_url` as boilerplate.

The biggest value added would be if the CI tools can detect that we're a PR, and run check.py in strict mode on the files in that PR.

**Comment by hbogner** [comment]
Just to clarify, privacy_policy_url is not the link to data license but to gdpr/cookies/tracking description?

**Comment by simonpoole** [comment]
Yes

**Comment by andrewharvey** [comment]
I'm mildly against making this mandatory, and would support it being a nice to have. If there is no privacy policy then consumers should just treat this as you have no privacy when accessing the services.

Since others mentioned many sources don't have a privacy policy, or it's unclear which privacy policy applies.

**Comment by grischard** [comment]
All new PRs are now checked for privacy_policy_url. Closing this for now; if someone wants to list and work on the existing sources like #439, open a new ticket.
