### ISSUE TITLE
Add LINZ (Land information new zealand) imagery layers

### ISSUE THREAD

**Issue by robinpaulson** [osmlab/editor-layer-index#70]
News item here:
http://www.scoop.co.nz/stories/PA1404/S00416/aerial-imagery-now-online-for-reuse.htm

imagery and licences here (CC):
https://data.linz.govt.nz/x/vuozYk

There are lots of layers, I think 42. I'm not entirely conversant with json, but if someone could explain the format clearly, I should be able to take part in making the json files myself.

**Comment by simon04** [comment]
Concerning of aerial images: The layer to go is https://creativecommons.org/licenses/by/3.0/nz/ since it combines all individual aerial layers. Many aerial layers are licensed [CC BY 3.0 NZ](https://data.linz.govt.nz/license/attribution-3-0-new-zealand/) which is not compatible with OSM unless a special agreement can be made. When the license question is clarified, an API key is required as explained on https://data.linz.govt.nz/set/2-nz-aerial-imagery/webservices/

**Comment by andrewharvey** [comment]
I'm in talks with LINZ about the licensing question. LINZ did provide an explicit permission previously, but I'm seeking to clarify this covers imagery as well, and make this more legally solid by using the waivers from the OSMF https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/.

**Comment by andrewharvey** [comment]
I've received a positive response from LINZ. They have completed the OSMF waiver (slightly tweaked for the NZ CC BY license)

https://wiki.openstreetmap.org/wiki/File:OSM_waiver_-_LINZ.pdf

PR at #334
