### ISSUE TITLE
Maxar Australian Bushfire Imagery

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/editor-layer-index#763]
Maxar have generously donated some satellite imagery of Australian bushfire affected
areas and they explicitly allow tracing for OSM,
https://blog.maxar.com/open-data-program/2020/open-data-response-to-the-australian-wildfires.

I've posted to the local mailing list on how to use these layers in JOSM and iD https://lists.openstreetmap.org/pipermail/talk-au/2020-January/013499.html.

Although it would be great to have these work out the box, I'm not sure ELI is quite setup to deal with this because:

- There are a lot of different layers (covering different dates), is this a problem?
- Because iD only ingests updates each release, even if I keep ELI master up to date, end iD users would rarely see current imagery layers (though JOSM users who point their imagery sources to ELI would).

Is it worth indexing this in ELI?

@grischard I know you had concerns about file size, but I think the more sources the better, if downloads become too large that's a good problem to have and can be solved in other ways on the software level, not the ELI index level.

**Comment by grischard** [comment]
I've had concerns about *unnecessary* file size, but this would be very good to have. You are correct in your other concerns though, iD doesn't use the 'live' version of ELI, and only refreshes on new releases. Users might get imagery that's stale. In this use case, it might unfortunately be better to send users to a webpage.

For the same reason, we don't integrate OpenAerialMap.

Hopefully work on #586 will change this one day, with the lifetime of the ELI metadata vector tiles determining how recent your imagery information is.

On the other hand, you could add that webpage to the community index, which iD shows when someone saves a changeset.

**Comment by andrewharvey** [comment]
as an aside @vincentsarago has also been working with this data and seemed to have success loading in these as COG, but looks like still through a proxy service to convert to tiles. Not sure if we should use something like that or stick with loading these into Mapbox. See https://twitter.com/_VincentS_/status/1218221955423391744.

See also my scripts for loading this data at https://gist.github.com/andrewharvey/57da8ad7f9f425d4c811e6cd33b2fdcb

**Comment by vincentsarago** [comment]
Hey @andrewharvey thanks for the mention. 

So because files are stored as Cloud Optimized Geotiff, it's is really easy and cheap to create a proxy tile server without the need to store the full files. 

 There are multiple repo and fork but the main 2 solutions are: 
- https://github.com/radiantearth/tiles.rdnt.io
- https://github.com/vincentsarago/lambda-tiler

We at DevellopementSeed, have also been working on virtual mosaic for COG (see https://medium.com/devseed/cog-talk-part-2-mosaics-bbbf474e66df) and still based on using serverless technology to create the tiles dynamically.

I've published 2 mosaics for pre-event images (there is just not enought post-event imagery for now to create usefull mosaic). Mosaic and tiles creation are done using https://github.com/developmentseed/cogeo-mosaic


#### Pre-Event Australia fire
- mosaic id: `6b6f479fbacd9a42e9e38bc5c0c6889f009beae13b07742ec4a1648f`
- tilejson: `https://cogeo.xyz/tiles/6b6f479fbacd9a42e9e38bc5c0c6889f009beae13b07742ec4a1648f/tilejson.json`
- wmts: `https://cogeo.xyz/tiles/6b6f479fbacd9a42e9e38bc5c0c6889f009beae13b07742ec4a1648f/wmts`
- tile url: `https://cogeo.xyz/tiles/6b6f479fbacd9a42e9e38bc5c0c6889f009beae13b07742ec4a1648f/{z}/{x}/{y}.png`

Feel free to use `cogeo.xyz` endpoint (hosted by devellopmentseed)

**Comment by andrewharvey** [comment]
> I've had concerns about unnecessary file size, but this would be very good to have. You are correct in your other concerns though, iD doesn't use the 'live' version of ELI, and only refreshes on new releases. Users might get imagery that's stale. In this use case, it might unfortunately be better to send users to a webpage.

After thinking this over, I do think we should gobble up anything that could be useful, irrespective of currency and file size concerns.

JOSM users can still benefit if they swap their sources over to ELI, and #765 would help even if you don't swap your imagery source in JOSM since you can browse at https://osmlab.github.io/editor-layer-index/ and load with remote control.

Agreed, I hope one eventually iD will pull in ELI master.

@vincentsarago That's awesome, I think it's easier just to use your cogeo.xyz end point.

**Comment by andrewharvey** [comment]
@vincentsarago do you think it's worth running a CDN in front of cogeo.xyz to cache tiles? I can't tell if the slow speeds are my internet or cogeo.xyz.

**Comment by vincentsarago** [comment]
yes tiles are not cached so it might be slow, I'll see if we can add a caching layer next week.

**Comment by grischard** [comment]
@andrewharvey should #766 really close this?

**Comment by andrewharvey** [comment]
@grischard Yes #766 closes this for now, we can add a layer for post event as more becomes available from Maxar.

**Comment by andrewharvey** [comment]
@vincentsarago sorry to bug you again, but any reason for using png? Looks like jpg tiles work and are much smaller. Since we don't use transparency, seems like jpg is better.

I setup a CDN on bunnyCDN, I guess you have no complains if I front this and update editor layer index to use the CDN?

**Comment by vincentsarago** [comment]
@andrewharvey sure you can pass `.jpg` for the tiles `https://cogeo.xyz/tiles/6b6f479fbacd9a42e9e38bc5c0c6889f009beae13b07742ec4a1648f/{zoom}/{x}/{y}.jpg` (you can also use webp if you want)
